# Generated by Django 4.1.7 on 2023-02-20 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appointment_created_at_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 20, 13, 58, 9, 478418), default=datetime.datetime(2023, 2, 20, 13, 58, 9, 478418)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 13, 58, 9, 478418)),
        ),
    ]
