# Generated by Django 4.1.7 on 2023-02-20 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_title_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 20, 19, 41, 28, 31525), default=datetime.datetime(2023, 2, 20, 19, 41, 28, 31525)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 19, 41, 28, 31525)),
        ),
    ]
