# Generated by Django 4.1.7 on 2023-02-21 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appointment_created_at_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 21, 11, 18, 57, 95155), default=datetime.datetime(2023, 2, 21, 11, 18, 57, 95155)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 18, 57, 87153)),
        ),
    ]
