# Generated by Django 4.1.7 on 2023-02-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_appointment_created_at_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 21, 11, 19, 10, 981458), default=datetime.datetime(2023, 2, 21, 11, 19, 10, 981458)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 19, 10, 981458)),
        ),
    ]
