# Generated by Django 4.1.7 on 2023-02-21 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_appointment_created_at_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 21, 15, 35, 27, 607748), default=datetime.datetime(2023, 2, 21, 15, 35, 27, 607748)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 35, 27, 607748)),
        ),
    ]
