# Generated by Django 4.1.7 on 2023-02-23 12:32

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_appointment_created_at_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 23, 13, 32, 48, 335517), default=datetime.datetime(2023, 2, 23, 13, 32, 48, 335517)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, validators=[api.models.Appointment.validate_date]),
        ),
    ]
