# Generated by Django 4.1.7 on 2023-02-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 2, 23, 14, 16, 24, 853686), default=datetime.datetime(2023, 2, 23, 14, 16, 24, 853686)),
        ),
    ]
